export function getChampionPrimaryRole(champion: string): string {
  const roles: Record<string, string> = {
    // Top
    Aatrox: "Top",
    Akali: "Top",
    Ambessa: "Top",
    Camille: "Top",
    "Cho'Gath": "Top",
    Darius: "Top",
    "Dr. Mundo": "Top",
    Fiora: "Top",
    Gangplank: "Top",
    Garen: "Top",
    Gnar: "Top",
    Gragas: "Top",
    Gwen: "Top",
    Heimerdinger: "Top",
    Illaoi: "Top",
    Irelia: "Top",
    Jax: "Top",
    Jayce: "Top",
    Kayle: "Top",
    Kennen: "Top",
    Kled: "Top",
    "K'Sante": "Top",
    Malphite: "Top",
    Mordekaiser: "Top",
    Nasus: "Top",
    Olaf: "Top",
    Ornn: "Top",
    Pantheon: "Top",
    Quinn: "Top",
    Renekton: "Top",
    Riven: "Top",
    Rumble: "Top",
    Sett: "Top",
    Shen: "Top",
    Singed: "Top",
    Sion: "Top",
    "Tahm Kench": "Top",
    Teemo: "Top",
    Tryndamere: "Top",
    Urgot: "Top",
    Volibear: "Top",
    Wukong: "Top",
    Yasuo: "Mid",
    Yone: "Mid",
    Yorick: "Top",

    // Jungle
    Amumu: "Jungle",
    "Bel'Veth": "Jungle",
    Briar: "Jungle",
    Diana: "Jungle",
    Ekko: "Jungle",
    Elise: "Jungle",
    Evelynn: "Jungle",
    Fiddlesticks: "Jungle",
    Graves: "Jungle",
    Hecarim: "Jungle",
    Ivern: "Jungle",
    "Jarvan IV": "Jungle",
    Karthus: "Jungle",
    Kayn: "Jungle",
    "Kha'Zix": "Jungle",
    Kindred: "Jungle",
    "Lee Sin": "Jungle",
    LeeSin: "Jungle",
    Lillia: "Jungle",
    "Master Yi": "Jungle",
    MasterYi: "Jungle",
    Nidalee: "Jungle",
    Nocturne: "Jungle",
    Nunu: "Jungle",
    "Nunu & Willump": "Jungle",
    Poppy: "Jungle",
    Rammus: "Jungle",
    "Rek'Sai": "Jungle",
    Rengar: "Jungle",
    Sejuani: "Jungle",
    Shaco: "Jungle",
    Shyvana: "Jungle",
    Skarner: "Jungle",
    Taliyah: "Jungle",
    Trundle: "Jungle",
    Udyr: "Jungle",
    Vi: "Jungle",
    Viego: "Jungle",
    Warwick: "Jungle",
    "Xin Zhao": "Jungle",
    Zac: "Jungle",

    // Mid
    Ahri: "Mid",
    Akshan: "Mid",
    Anivia: "Mid",
    Annie: "Mid",
    "Aurelion Sol": "Mid",
    Aurora: "Mid",
    Azir: "Mid",
    Cassiopeia: "Mid",
    Corki: "Mid",
    Fizz: "Mid",
    Galio: "Mid",
    Hwei: "Mid",
    Kassadin: "Mid",
    Katarina: "Mid",
    LeBlanc: "Mid",
    Lissandra: "Mid",
    Lux: "Mid",
    Malzahar: "Mid",
    Mel: "Mid",
    Naafiri: "Mid",
    Neeko: "Mid",
    Orianna: "Mid",
    Qiyana: "Mid",
    Ryze: "Mid",
    Swain: "Mid",
    Sylas: "Mid",
    Syndra: "Mid",
    Talon: "Mid",
    "Twisted Fate": "Mid",
    Veigar: "Mid",
    "Vel'Koz": "Mid",
    Vex: "Mid",
    Viktor: "Mid",
    Vladimir: "Mid",
    Xerath: "Mid",
    Zed: "Mid",
    Ziggs: "Mid",
    Zoe: "Mid",

    // ADC
    Aphelios: "ADC",
    Ashe: "ADC",
    Caitlyn: "ADC",
    Draven: "ADC",
    Ezreal: "ADC",
    Jhin: "ADC",
    Jinx: "ADC",
    "Kai'Sa": "ADC",
    Kalista: "ADC",
    "Kog'Maw": "ADC",
    Lucian: "ADC",
    "Miss Fortune": "ADC",
    MissFortune: "ADC",
    Nilah: "ADC",
    Samira: "ADC",
    Sivir: "ADC",
    Smolder: "ADC",
    Tristana: "ADC",
    Twitch: "ADC",
    Varus: "ADC",
    Vayne: "ADC",
    Xayah: "ADC",
    Zeri: "ADC",

    // Support
    Alistar: "Support",
    Bard: "Support",
    Blitzcrank: "Support",
    Braum: "Support",
    Brand: "Support",
    Janna: "Support",
    Karma: "Support",
    Leona: "Support",
    Lulu: "Support",
    Milio: "Support",
    Morgana: "Support",
    Nami: "Support",
    Nautilus: "Support",
    Pyke: "Support",
    Rakan: "Support",
    Rell: "Support",
    "Renata Glasc": "Support",
    Senna: "Support",
    Seraphine: "Support",
    Sona: "Support",
    Soraka: "Support",
    Taric: "Support",
    Thresh: "Support",
    Yuumi: "Support",
    Zilean: "Support",
    Zyra: "Support"
  };

  return roles[champion] || "Unknown";
}
